---
name: Check for linting Markdown

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.md"
permissions: read-all
jobs:
  lint-shell-script:
    name: run markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: "**/*.md"
