---
name: Check for linting Markdown

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.md"
permissions: read-all
jobs:
  lint-shell-script:
    name: run markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: "**/*.md"
