---
name: Check for linting Markdown

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.md"
permissions: read-all
jobs:
  lint-shell-script:
    name: run markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          globs: "**/*.md"
